export const types = {
  SET_DATA: "SET_DATA",
  SET_INPUT_VALUE: "SET_INPUT_VALUE",
  SET_SELECT_VALUE: "SET_SELECT_VALUE",
  UPDATE_DASHBOARD: "UPDATE_DASHBOARD",
  SET_LOADING: "SET_LOADING",
} as const;
